# Generated by Django 3.2.25 on 2024-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimmachungkhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaChungKhoan', models.CharField(max_length=20)),
                ('TenCongTy', models.CharField(max_length=255)),
                ('TenNganh', models.CharField(max_length=255)),
            ],
        ),
    ]
